apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: okapi
  namespace: folio
spec:
  podManagementPolicy: OrderedReady
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: apps.deployment-folio-okapi
  serviceName: okapi
  template:
    metadata:
      creationTimestamp: null
      labels:
        workload.user.cattle.io/workloadselector: apps.deployment-folio-okapi
      namespace: folio
    spec:
      affinity:
        podAffinity: {}
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: workload.user.cattle.io/workloadselector
                      operator: In
                      values:
                        - deployment-folio-okapi
                topologyKey: kubernetes.io/hostname
              weight: 100
      containers:
        - envFrom:
            - secretRef:
                name: okapi-config
                optional: false
          image: jed.ocir.io/axhxgarudf1b/okapi:5.3.0-cluster-newrelic
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 20
            httpGet:
              path: /_/proxy/health
              port: 9130
              scheme: HTTP
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 1
          name: okapi
          readinessProbe:
            failureThreshold: 20
            httpGet:
              path: /_/proxy/health
              port: 9130
              scheme: HTTP
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            limits:
              cpu: 2500m
              memory: 16000Mi
            requests:
              cpu: 500m
              memory: 2000Mi
          securityContext:
            capabilities: {}
          startupProbe:
            failureThreshold: 60
            httpGet:
              path: /_/proxy/health
              port: 9130
              scheme: HTTP
            initialDelaySeconds: 300
            periodSeconds: 60
            successThreshold: 1
            timeoutSeconds: 1
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /usr/local/bin/folio/okapi/hazelcast.xml
              name: vol-fkhny
              subPath: okapi/hazelcast.xml
      dnsPolicy: ClusterFirst
      imagePullSecrets:
        - name: oracle-reg
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - name: vol-fkhny
          persistentVolumeClaim:
            claimName: medad-ils
  updateStrategy:
    rollingUpdate:
      partition: 0
    type: RollingUpdate
