apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: okapi
  namespace: folio
spec:
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Retain
    whenScaled: Retain
  podManagementPolicy: OrderedReady
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: apps.deployment-folio-okapi
  serviceName: okapi
  template:
    metadata:
      creationTimestamp: null
      labels:
        workload.user.cattle.io/workloadselector: apps.deployment-folio-okapi
      namespace: folio
    spec:
      affinity:
        podAffinity: {}
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: workload.user.cattle.io/workloadselector
                      operator: In
                      values:
                        - deployment-folio-okapi
                topologyKey: kubernetes.io/hostname
              weight: 100
      containers:
        - envFrom:
            - secretRef:
                name: okapi-config
                optional: false
            - secretRef:
                name: new-relic-okapi
                optional: false
          image: jed.ocir.io/axhxgarudf1b/okapi:5.3.0-cluster-newrelic
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 20
            httpGet:
              path: /_/proxy/health
              port: 9130
              scheme: HTTP
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 1
          name: okapi
          readinessProbe:
            failureThreshold: 20
            httpGet:
              path: /_/proxy/health
              port: 9130
              scheme: HTTP
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            limits:
              cpu: "2"
              memory: 16000Mi
            requests:
              cpu: "1"
              memory: 8000Mi
          securityContext:
            capabilities: {}
          startupProbe:
            failureThreshold: 30
            httpGet:
              path: /_/proxy/health
              port: 9130
              scheme: HTTP
            initialDelaySeconds: 120
            periodSeconds: 60
            successThreshold: 1
            timeoutSeconds: 1
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      imagePullSecrets:
        - name: oracle-reg
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
  updateStrategy:
    rollingUpdate:
      partition: 0
    type: RollingUpdate
