apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  finalizers:
    - kubernetes.io/pvc-protection
  name: medad-ils
  namespace: folio
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: nfs-folio
  volumeMode: Filesystem
  volumeName: pvc-34c875d2-2285-4e29-a411-8963fed4ce18
