apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  finalizers:
    - kubernetes.io/pvc-protection
  name: medad-ils
  namespace: folio
spec:
  accessModes:
    - ReadWriteOnce
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: oci
  volumeMode: Filesystem
  volumeName: medad-ils
