apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  finalizers:
    - kubernetes.io/pvc-protection
  name: nfs-folio-pvc
  namespace: folio
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi
  selector:
    matchLabels:
      failure-domain.beta.kubernetes.io/zone: ME-JEDDAH-1-AD-1
  storageClassName: oci
  volumeMode: Filesystem
  volumeName: nfs-folio-pv
