apiVersion: v1
data:
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIC/jCCAeagAwIBAgIBADANBgkqhkiG9w0BAQsFADAVMRMwEQYDVQQDEwprdWJl
    cm5ldGVzMB4XDTIyMTIwNzE0MTkzN1oXDTMyMTIwNDE0MTkzN1owFTETMBEGA1UE
    AxMKa3ViZXJuZXRlczCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAMOH
    GJPIEF0ow44Zi3HjP5o2NvmmP/vwzXtUXlBphK+/pyT7UYbQ4TGOE/4zujASzgyp
    6pA/sjJACtquV2qUT3KxAqyKOPPexuEbEHJOiSnEQVFP18e++zjgiqv4Casdjjx4
    GVJAfBL6/rO5P/7Nk7Q6LSa39/ZOMR/zqkRzQopK+J2TqJZr4rxb3jbCfFVn0AS/
    j8T8yKhaD14s1zLysuovfknZWHIiXtxvPXO70Bxi0VNoZiXsRHuqxqzKfDUETecI
    1DR38xwBJ/QeE25QshYxBviHNGq4pDzrYijL/ZIMatbKaoCefHO5pgki1AU4kDxD
    V6kwRyS7lcBwNDJv7PUCAwEAAaNZMFcwDgYDVR0PAQH/BAQDAgKkMA8GA1UdEwEB
    /wQFMAMBAf8wHQYDVR0OBBYEFL2qcBPGPXxRqbeTZZoL0tw1gjCZMBUGA1UdEQQO
    MAyCCmt1YmVybmV0ZXMwDQYJKoZIhvcNAQELBQADggEBAGEVqj/dML1WS4ck7UN3
    lm4ut/+W29VZgl9AA/w935i02o08+73Us52GdTmMUp0hbhR2lCMVUQ3NshuF9O1b
    2SPYItsOAcvFjMnXU9lAytI1m0SE7VN41eKottKE/mqQa3BbMqTCsCb3G0jxF8An
    y7AlRiZuGniPAOQfATc9/q5Bfxa89eitO28woJ/CQ8qkWI0naEnkrZD0cIcFWEV8
    DwDGo91ARMKYFgjaYMEkY1AmpIdKmxPdxPGZB6XsZ50h1aFxd+5RKhFGJxNvawwW
    SY0tIu/62HzAFEoAdQmQjDKDZHiSdfMzSfX9O27yfeVUjAcS9Qk7W6peFZzgKx4j
    /bk=
    -----END CERTIFICATE-----
kind: ConfigMap
metadata:
  name: kube-root-ca.crt
  namespace: folio
