apiVersion: v1
data:
  db_host: MTAuMC4xMC4zNQ==
  db_name: bWVkYWRfbGRw
  db_password: QGFzMTIz
  db_port: NTQzMg==
  db_username: bGRwYWRtaW4=
  okapi_db_host: MTAuMC4xMC4zNQ==
  okapi_db_name: b2thcGlfbW9kdWxlcw==
  okapi_db_password: YjVXOCM1SjQmUitYOEF5dQ==
  okapi_db_port: NTQzMg==
  okapi_db_username: bWVkYWRfazhzX21hc3Rlcg==
  okapi_password: TWVkYWRfYWRtaW5AMTIzIA==
  okapi_tenant: bWVkYWQ=
  okapi_url: aHR0cDovL29rYXBp
  okapi_user: bWVkYWRfYWRtaW4=
  super_db_password: YjVXOCM1SjQmUitYOEF5dQ==
  super_db_username: bWVkYWRfazhzX21hc3Rlcg==
kind: Secret
metadata:
  name: ldp
  namespace: folio
type: Opaque
