apiVersion: v1
data:
  JAVA_OPTIONS: LVhYOk1heFJBTVBlcmNlbnRhZ2U9NjYuMCAtamF2YWFnZW50Oi91c3IvbG9jYWwvbmV3cmVsaWMvbmV3cmVsaWMuamFy
  NEW_RELIC_LICENSE_KEY: YTRmYjViMmU1ODdkNGJmMDMzOWU0YWZiYjdlMTJjNzJGRkZGTlJBTA==
  NEW_RELIC_LOG_ENABLED: ZmFsc2U=
kind: Secret
metadata:
  name: new-relic
  namespace: folio
type: Opaque
