apiVersion: apps/v1
kind: Deployment
metadata:
  name: mod-reports
  namespace: folio
spec:
  progressDeadlineSeconds: 600
  replicas: 0
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-folio-mod-reports
  template:
    metadata:
      creationTimestamp: null
      labels:
        workload.user.cattle.io/workloadselector: deployment-folio-mod-reports
      namespace: folio
    spec:
      containers:
        - env:
            - name: DOCKER_CHROME_DRIVER_PATH
              value: /usr/bin/chromedriver
            - name: REPORT_RENDER_PATH
              value: /usr/verticles/build/index.html
          envFrom:
            - secretRef:
                name: mod-reports
                optional: false
            - secretRef:
                name: new-relic
                optional: false
          image: jed.ocir.io/axhxgarudf1b/mod-reports:1.5.9
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 10
            httpGet:
              path: /admin/health
              port: 8081
              scheme: HTTP
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 1
          name: mod-reports
          readinessProbe:
            failureThreshold: 5
            httpGet:
              path: /admin/health
              port: 8081
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            limits:
              cpu: 400m
              memory: 5000Mi
            requests:
              cpu: 20m
              memory: 128Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities: {}
            privileged: false
            readOnlyRootFilesystem: false
            runAsNonRoot: false
          startupProbe:
            failureThreshold: 20
            httpGet:
              path: /admin/health
              port: 8081
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 20
            successThreshold: 1
            timeoutSeconds: 1
          stdin: true
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          tty: true
      dnsPolicy: ClusterFirst
      imagePullSecrets:
        - name: oracle-reg
      initContainers:
        - envFrom:
            - secretRef:
                name: folio-analytics-queries
                optional: false
          image: jed.ocir.io/axhxgarudf1b/folio-analytics-queries:1.5.2
          imagePullPolicy: Always
          name: folio-analytics-queries
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
