apiVersion: apps/v1
kind: Deployment
metadata:
  name: mod-inventory-storage
  namespace: folio
spec:
  minReadySeconds: 30
  progressDeadlineSeconds: 300
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-folio-mod-inventory-storage
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mod-inventory-storage
        workload.user.cattle.io/workloadselector: deployment-folio-mod-inventory-storage
      namespace: folio
    spec:
      affinity:
        podAffinity: {}
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - mod-inventory-storage
                topologyKey: kubernetes.io/hostname
              weight: 1
      containers:
        - env:
            - name: JAVA_OPTIONS
              value: -Xms128m -Xmx9000m -javaagent:/usr/local/newrelic/newrelic.jar
          envFrom:
            - secretRef:
                name: db-connect
                optional: true
            - secretRef:
                name: new-relic
                optional: false
          image: jed.ocir.io/axhxgarudf1b/mod-inventory-storage:27.1.4.1.0.4
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 10
            httpGet:
              path: /admin/health
              port: 8081
              scheme: HTTP
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 1
          name: mod-inventory-storage
          readinessProbe:
            failureThreshold: 5
            httpGet:
              path: /admin/health
              port: 8081
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            limits:
              cpu: 600m
              memory: 10000Mi
            requests:
              cpu: 20m
              memory: 128Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities: {}
            privileged: false
            procMount: Default
            readOnlyRootFilesystem: false
            runAsNonRoot: false
          startupProbe:
            failureThreshold: 20
            httpGet:
              path: /admin/health
              port: 8081
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 1
          stdin: true
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          tty: true
      dnsPolicy: ClusterFirst
      imagePullSecrets:
        - name: oracle-reg
