apiVersion: apps/v1
kind: Deployment
metadata:
  name: mod-data-export
  namespace: folio
spec:
  minReadySeconds: 30
  progressDeadlineSeconds: 300
  replicas: 0
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-folio-mod-data-export
  template:
    metadata:
      creationTimestamp: null
      labels:
        workload: folio_module
        workload.user.cattle.io/workloadselector: deployment-folio-mod-data-export
      namespace: folio
    spec:
      containers:
        - envFrom:
            - secretRef:
                name: db-connect
                optional: true
            - secretRef:
                name: oci-object-storage
                optional: false
            - secretRef:
                name: mod-data-export
                optional: false
          image: folioorg/mod-data-export:5.0.4
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 10
            httpGet:
              path: /admin/health
              port: 8081
              scheme: HTTP
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 1
          name: mod-data-export
          readinessProbe:
            failureThreshold: 5
            httpGet:
              path: /admin/health
              port: 8081
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            limits:
              cpu: 200m
              memory: 5000Mi
            requests:
              cpu: 20m
              memory: 128Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities: {}
            privileged: false
            procMount: Default
            readOnlyRootFilesystem: false
            runAsNonRoot: false
          startupProbe:
            failureThreshold: 15
            httpGet:
              path: /admin/health
              port: 8081
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 15
            successThreshold: 1
            timeoutSeconds: 1
          stdin: true
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          tty: true
          volumeMounts:
            - mountPath: /usr/verticles/storage/files
              name: mod-data-export
              subPath: mod-data-export
      dnsPolicy: ClusterFirst
      imagePullSecrets:
        - name: oracle-reg
      nodeSelector:
        product: ils
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      tolerations:
        - effect: NoExecute
          key: product
          operator: Equal
          value: ils
      volumes:
        - name: mod-data-export
          persistentVolumeClaim:
            claimName: medad-ils
