apiVersion: apps/v1
kind: Deployment
metadata:
  name: mod-ai-operations
  namespace: folio
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: apps.deployment-folio-mod-ai-operations
  template:
    metadata:
      creationTimestamp: null
      labels:
        workload.user.cattle.io/workloadselector: apps.deployment-folio-mod-ai-operations
      name: mod-ai-operations
      namespace: folio
    spec:
      containers:
        - env:
            - name: S3_BUCKET
              value: ai-operations
            - name: S3_URL_EXPIRY
              value: "300"
            - name: S3_OBJECT_EXPIRY
              value: "1"
            - name: S3_BUCKET
              value: ai-operations-stg
          envFrom:
            - secretRef:
                name: db-connect
            - secretRef:
                name: openai-secrets
                optional: false
            - secretRef:
                name: oci-object-storage
                optional: false
          image: jed.ocir.io/axhxgarudf1b/mod-ai-operations:1.0.11
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 10
            httpGet:
              path: /admin/health
              port: 8081
              scheme: HTTP
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 1
          name: mod-ai-operations
          ports:
            - containerPort: 8081
              name: 8081tcp02
              protocol: TCP
          readinessProbe:
            failureThreshold: 5
            httpGet:
              path: /admin/health
              port: 8081
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            limits:
              cpu: 300m
              memory: 2000Mi
            requests:
              cpu: 20m
              memory: 128Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities: {}
            privileged: false
            readOnlyRootFilesystem: false
            runAsNonRoot: false
          startupProbe:
            failureThreshold: 20
            httpGet:
              path: /admin/health
              port: 8081
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          stdin: true
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          tty: true
      dnsPolicy: ClusterFirst
      imagePullSecrets:
        - name: oracle-reg
