apiVersion: apps/v1
kind: Deployment
metadata:
  name: mod-circulation-item
  namespace: folio
spec:
  minReadySeconds: 60
  progressDeadlineSeconds: 300
  replicas: 0
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: apps.deployment-folio-mod-circulation-item
  template:
    metadata:
      creationTimestamp: null
      labels:
        workload: folio_module
        workload.user.cattle.io/workloadselector: apps.deployment-folio-mod-circulation-item
      name: mod-circulation-item
      namespace: folio
    spec:
      affinity: {}
      containers:
        - envFrom:
            - secretRef:
                name: db-connect
                optional: true
            - secretRef:
                name: oci-object-storage
                optional: false
          image: folioorg/mod-circulation-item:1.0.0
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 10
            httpGet:
              path: /admin/health
              port: 8081
              scheme: HTTP
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 1
          name: mod-circulation-item
          readinessProbe:
            failureThreshold: 5
            httpGet:
              path: /admin/health
              port: 8081
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            limits:
              cpu: 500m
              memory: 6000Mi
            requests:
              cpu: 50m
              memory: 512Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities: {}
            privileged: false
            procMount: Default
            readOnlyRootFilesystem: false
            runAsNonRoot: false
          startupProbe:
            failureThreshold: 20
            httpGet:
              path: /admin/health
              port: 8081
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 1
          stdin: true
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          tty: true
      dnsPolicy: ClusterFirst
