apiVersion: apps/v1
kind: Deployment
metadata:
  name: mod-data-import
  namespace: folio
spec:
  minReadySeconds: 30
  progressDeadlineSeconds: 300
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-folio-mod-data-import
  template:
    metadata:
      creationTimestamp: null
      labels:
        workload.user.cattle.io/workloadselector: deployment-folio-mod-data-import
      namespace: folio
    spec:
      containers:
        - envFrom:
            - secretRef:
                name: db-connect
                optional: false
          image: jed.ocir.io/axhxgarudf1b/mod-data-import:3.1.1.1.0.6
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 30
            httpGet:
              path: /admin/health
              port: 8081
              scheme: HTTP
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 5
          name: mod-data-import
          readinessProbe:
            failureThreshold: 20
            httpGet:
              path: /admin/health
              port: 8081
              scheme: HTTP
            periodSeconds: 20
            successThreshold: 1
            timeoutSeconds: 5
          resources:
            limits:
              cpu: "1"
              memory: 6000Mi
            requests:
              cpu: 100m
              memory: 512Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities: {}
            privileged: false
            procMount: Default
            readOnlyRootFilesystem: false
            runAsNonRoot: false
          startupProbe:
            failureThreshold: 100
            httpGet:
              path: /admin/health
              port: 8081
              scheme: HTTP
            initialDelaySeconds: 600
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 5
          stdin: true
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          tty: true
          volumeMounts:
            - mountPath: /usr/verticles/storage/upload
              name: mod-data-import
              subPath: mod-data-import
      dnsPolicy: ClusterFirst
      imagePullSecrets:
        - name: oracle-reg
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - name: mod-data-import
          persistentVolumeClaim:
            claimName: medad-ils
