apiVersion: apps/v1
kind: Deployment
metadata:
  name: mod-eusage-reports
  namespace: folio
spec:
  progressDeadlineSeconds: 600
  replicas: 0
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: apps.deployment-folio-mod-eusage-reports
  template:
    metadata:
      creationTimestamp: null
      labels:
        workload.user.cattle.io/workloadselector: apps.deployment-folio-mod-eusage-reports
    spec:
      affinity: {}
      containers:
        - envFrom:
            - secretRef:
                name: db-connect
                optional: false
          image: folioorg/mod-eusage-reports:2.1.1
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 10
            httpGet:
              path: /admin/health
              port: 8081
              scheme: HTTP
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 1
          name: mod-eusage-reports
          ports:
            - containerPort: 8081
              name: tcp
              protocol: TCP
          readinessProbe:
            failureThreshold: 5
            httpGet:
              path: /admin/health
              port: 8081
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            limits:
              cpu: 200m
              memory: 5000Mi
            requests:
              cpu: 20m
              memory: 128Mi
          startupProbe:
            failureThreshold: 15
            httpGet:
              path: /admin/health
              port: 8081
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      nodeSelector:
        product: ils
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      tolerations:
        - effect: NoExecute
          key: product
          operator: Equal
          value: ils
