apiVersion: apps/v1
kind: Deployment
metadata:
  name: ssh-agent
  namespace: folio
spec:
  progressDeadlineSeconds: 600
  replicas: 0
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: apps.deployment-folio-ssh-agent
  template:
    metadata:
      creationTimestamp: null
      labels:
        workload.user.cattle.io/workloadselector: apps.deployment-folio-ssh-agent
      namespace: folio
    spec:
      containers:
        - args:
            - apt-get update && apt-get install -y openssh-client && while true; do sleep 86400; done
          command:
            - /bin/bash
            - -c
          image: ubuntu:latest
          imagePullPolicy: Always
          name: container-0
          resources: {}
          securityContext:
            allowPrivilegeEscalation: true
            capabilities:
              add:
                - ALL
            privileged: true
            readOnlyRootFilesystem: false
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /mnt
              name: vol-up9kd
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - name: vol-up9kd
          nfs:
            path: /Medad-LSP-FS/
            server: 10.0.10.8
