apiVersion: v1
kind: Service
metadata:
  name: mod-serials-management
  namespace: folio
spec:
  ports:
    - name: http
      port: 8081
      protocol: TCP
      targetPort: 8080
  selector:
    workload.user.cattle.io/workloadselector: apps.deployment-folio-mod-serials-management
  sessionAffinity: None
  type: ClusterIP
