apiVersion: v1
kind: Service
metadata:
  name: mod-circulation
  namespace: folio
spec:
  ports:
    - port: 8081
      protocol: TCP
      targetPort: 8081
  selector:
    workload.user.cattle.io/workloadselector: deployment-folio-mod-circulation
  sessionAffinity: None
  type: ClusterIP
