apiVersion: v1
kind: Service
metadata:
  name: mod-event-config
  namespace: folio
spec:
  ports:
    - name: default
      port: 8081
      protocol: TCP
      targetPort: 8081
  selector:
    workload.user.cattle.io/workloadselector: deployment-folio-mod-event-config
  sessionAffinity: None
  type: ClusterIP
