apiVersion: v1
kind: Service
metadata:
  name: mod-login
  namespace: folio
spec:
  ports:
    - name: default
      port: 42
      protocol: TCP
      targetPort: 42
  selector:
    workload.user.cattle.io/workloadselector: deployment-folio-mod-login
  sessionAffinity: None
  type: ClusterIP
