apiVersion: v1
kind: Service
metadata:
  name: mod-graphql
  namespace: folio
spec:
  ports:
    - name: http
      port: 8081
      protocol: TCP
      targetPort: 3001
  selector:
    workload.user.cattle.io/workloadselector: apps.deployment-folio-mod-graphql
  sessionAffinity: None
  type: ClusterIP
