apiVersion: v1
kind: Service
metadata:
  name: mod-batch-print
  namespace: folio
spec:
  ports:
    - port: 8081
      protocol: TCP
      targetPort: 8081
  selector:
    workload.user.cattle.io/workloadselector: apps.deployment-folio-mod-batch-print
  sessionAffinity: None
  type: ClusterIP
