apiVersion: v1
kind: Service
metadata:
  name: my-release-influxdb
  namespace: folio
spec:
  ports:
    - name: http
      port: 8086
      protocol: TCP
      targetPort: http
    - name: rpc
      port: 8088
      protocol: TCP
      targetPort: rpc
    - name: http1
      port: 80
      protocol: TCP
      targetPort: 8086
  selector:
    app.kubernetes.io/component: influxdb
    app.kubernetes.io/instance: my-release
    app.kubernetes.io/name: influxdb
  sessionAffinity: None
  type: ClusterIP
