apiVersion: v1
kind: Service
metadata:
  name: okapi
  namespace: folio
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 9130
    - name: https
      port: 443
      protocol: TCP
      targetPort: 9130
    - name: okapi
      port: 9130
      protocol: TCP
      targetPort: 9130
    - name: metrics
      port: 9930
      protocol: TCP
      targetPort: 9930
    - name: metrics1
      port: 4191
      protocol: TCP
      targetPort: 4191
  selector:
    workload.user.cattle.io/workloadselector: apps.deployment-folio-okapi
  sessionAffinity: None
  type: ClusterIP
