apiVersion: v1
kind: Service
metadata:
  name: solr
  namespace: folio
spec:
  ports:
    - name: http-solr
      port: 8983
      protocol: TCP
      targetPort: 8983
  selector:
    workload.user.cattle.io/workloadselector: deployment-folio-solr
  sessionAffinity: None
  type: ClusterIP
