apiVersion: v1
kind: Service
metadata:
  name: stripes-medad-k8s-custom-stg
  namespace: folio
spec:
  ports:
    - name: port
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    workload.user.cattle.io/workloadselector: deployment-folio-stripes-medad-k8s-custom-stg
  sessionAffinity: None
  type: ClusterIP
